version: '2'
services:
  httpd:
    image: httpd:2.4-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/www
      - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf
    working_dir: /www
    links:
      - fpm 
  fpm:
#    image: php:5.6-fpm-alpine
    image: php:7.1-fpm-alpine
    ports:
      - "9000:9000"
    volumes:
      - .:/www
      - ./config/php.ini:/usr/local/etc/php/conf.d/app.ini
