version: '2'
services:
  httpd:
    image: httpd:2.4-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/www
      - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf
    working_dir: /www
    links:
      - fpm 
  fpm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/www
      - ./config/php.ini:/usr/local/etc/php/conf.d/app.ini
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - wordpress-db:/var/lib/mysql
volumes:
  wordpress-db: