version: '3.9'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/www
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf

  fpm:
    build:
      context: .
      target: base
    volumes:
      - .:/www
      - ./config/php.ini:/usr/local/etc/php/conf.d/app.ini

  composer:
    build:
      context: .
      target: composer
    volumes:
      - .:/www
    profiles:
      - utils

  phpcs:
    build:
      context: .
      target: phpcs
    volumes:
      - .:/app
    profiles:
      - utils
