version: '3.9'

services:
  php:
    build:
      context: .
      target: runtime
    volumes:
      - .:/app
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3

  composer:
    build:
      context: .
      target: composer
    volumes:
      - .:/app
    profiles:
      - utils

  phpcs:
    build:
      context: .
      target: phpcs
    volumes:
      - .:/app
    profiles:
      - utils
