version: '2'
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/www
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm 
  fpm:
#    image: php:5.6-fpm-alpine
    image: php:7.1-fpm-alpine
    ports:
      - "9000:9000"
    volumes:
      - .:/www
      - ./config/php.ini:/usr/local/etc/php/conf.d/app.ini